### ISSUE TITLE
s32z270dc2_rtu1_r52 build doesn't accept several float instructions

### ISSUE THREAD

**Issue by keith-packard** [zephyrproject-rtos/sdk-ng#577]
The s32z270dc2_rtu1_r52 includes a Cortex-R52 core with some options, but the 0.15.1 toolchain doesn't compile this code:
```
float
rintf (float x)
{
  float result;
  __asm__ volatile ("vrintx.f32\t%0, %1" : "=t" (result) : "t" (x));
  return result;
}
```
it produces this error:
```
$ arm-zephyr-eabi-gcc -mcpu=cortex-r52 -mfloat-abi=hard -mabi=aapcs -mfpu=vfpv3-d16 -mfloat-abi=hard -c foo.c
/tmp/ccVEnKB0.s: Assembler messages:
/tmp/ccVEnKB0.s:33: Error: selected processor does not support `vrintx.f32 s15,s15' in ARM mode
```
It looks like `-mfpu=vfp3-d16` makes the assembler fail to accept that instruction, which (I think) should be valid.

**Comment by keith-packard** [comment]
a second issue is that the toolchain doesn't appear to generate a multi-lib configuration which is compatible with this processor, ending up using `thumb/v7+fp/hard`

**Comment by stephanosio** [comment]
> It looks like `-mfpu=vfp3-d16` makes the assembler fail to accept that instruction, which (I think) should be valid.

[According to GCC, ARMv8-R (Cortex-R52) has either `fpv5-sp-d16` (single precision configuration) or `neon-fp-armv8` (double precision + Advanced SIMD configuration)](https://github.com/gcc-mirror/gcc/blob/16e2427f50c208dfe07d07f18009969502c25dc8/gcc/config/arm/arm-cpus.in#L710-L724), so `vfpv3-d16` FPU type is incorrect.

I will send a Zephyr-side patch to specify the correct FPU type for the Cortex-R52.

> a second issue is that the toolchain doesn't appear to generate a multi-lib configuration which is compatible with this processor, ending up using `thumb/v7+fp/hard`

In fact, we (or the upstream GCC, for that matter) currently do not have any dedicated multilibs for non-M profile ARMv8 targets. This is mainly because ARMv8-A and ARMv8-R can execute ARMv7-A and ARMv7-R code as-is, and there is little to gain by having dedicated ARMv8 multilibs.

**Comment by stephanosio** [comment]
Zephyr-side fix: https://github.com/zephyrproject-rtos/zephyr/pull/51377

**Comment by keith-packard** [comment]
Verified that this change enables these instructions in picolibc when built as a module
